# Kotlin
kotlin.code.style=official
# رم کامپایلر کاتلین از ۳ گیگابایت به ۱ گیگابایت کاهش یافت
kotlin.daemon.jvmargs=-Xmx1024M

# Gradle
# رم گریدل از ۳ گیگابایت به ۲ گیگابایت کاهش یافت (به همراه پشتیبانی از متن فارسی)
org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

# --- تنظیمات اختصاصی دور زدن محدودیت اندروید (Termux) ---
# جلوگیری از اجرای همزمان تسک‌ها 
org.gradle.parallel=false
# محدود کردن شدید تعداد کارگرها 
org.gradle.workers.max=1
# غیرفعال کردن سیستم نظارت بر فایل‌ها 
org.gradle.vfs.watch=false
org.gradle.daemon=false