# Kotlin
kotlin.code.style=official
# رم اختصاصی کامپایلر کاتلین برای IR و Compose HTML
kotlin.daemon.jvmargs=-Xmx2560M

# Gradle Standard & CI (GitHub Actions Balanced)
# رم هسته گریدل به همراه متاسپیس کنترل‌شده
org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
